# -*- coding: utf-8 -*-
"""working.......ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NooFtjlvkMpoFC7r8hgN6z_9QTLP4sJo
"""

import os, json, random, shutil
import numpy as np
from pathlib import Path
from PIL import Image
import torch, torch.nn as nn, torch.optim as optim
from torch.utils.data import DataLoader
import torchvision as tv
import torchvision.transforms as T
import gradio as gr
import cv2

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Running on:", device)

from google.colab import drive
drive.mount('/content/drive')

dataset_path = Path("/content/drive/MyDrive/PlantVillage")
print("Dataset path:", dataset_path)

# Find class folders (Tomato_, Potato_, Pepper_, Corn_, Rice_, Black_, Cinder_, Laterite_, Peat_, Yellow_ )
def find_class_roots(base: Path):
    roots = {}
    for root, dirs, files in os.walk(base):
        for d in dirs:
            if any(d.startswith(prefix) for prefix in ["Tomato_", "Potato_", "Pepper_", "Corn_", "Rice_", "Black_", "Cinder_", "Laterite_", "Peat_", "Yellow_"]):
                roots[d] = Path(root) / d
    return roots

class_dirs = find_class_roots(dataset_path)
if not class_dirs:
    raise RuntimeError(f"No class folders found under {dataset_path}.")
target_classes = list(class_dirs.keys())
print("Found classes:", target_classes)

#Train/val split
work_root = Path("/content/data")
train_dir, val_dir = work_root/"train", work_root/"val"
train_dir.mkdir(parents=True, exist_ok=True)
val_dir.mkdir(parents=True, exist_ok=True)

def copy_split(src_class_dir: Path, dst_train: Path, dst_val: Path, split=0.8, seed=42):
    imgs = [p for p in src_class_dir.iterdir() if p.suffix.lower() in [".jpg",".jpeg",".png",".bmp",".tif",".tiff",".webp"]]
    random.Random(seed).shuffle(imgs)
    cut = int(split * len(imgs))
    for p in imgs[:cut]:
        (dst_train/src_class_dir.name).mkdir(parents=True, exist_ok=True)
        shutil.copy(p, dst_train/src_class_dir.name/p.name)
    for p in imgs[cut:]:
        (dst_val/src_class_dir.name).mkdir(parents=True, exist_ok=True)
        shutil.copy(p, dst_val/src_class_dir.name/p.name)

for cls in target_classes:
    copy_split(class_dirs[cls], train_dir, val_dir)

print("Prepared split at:", work_root)

# 2. Data Preparation
# ============================================================
img_size = 224
tfm_train = tv.transforms.Compose([
    tv.transforms.Resize(256),
    tv.transforms.RandomResizedCrop(img_size, scale=(0.85, 1.0)),
    tv.transforms.RandomHorizontalFlip(),
    tv.transforms.ColorJitter(0.15, 0.15, 0.1, 0.02),
    tv.transforms.ToTensor(),
    tv.transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])
tfm_val = tv.transforms.Compose([
    tv.transforms.Resize(256),
    tv.transforms.CenterCrop(img_size),
    tv.transforms.ToTensor(),
    tv.transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])

train_ds = tv.datasets.ImageFolder(str(train_dir), transform=tfm_train)
val_ds   = tv.datasets.ImageFolder(str(val_dir),   transform=tfm_val)
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, num_workers=2, pin_memory=True)
print("Class order:", train_ds.classes)
print(train_ds.class_to_idx)

# 3. Model Setup (ResNet-50)
# ============================================================
model = tv.models.resnet50(weights=tv.models.ResNet50_Weights.DEFAULT)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, len(train_ds.classes))
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=25)

# ============================================================
# 4. Training Loop
# ============================================================
from google.colab import files # Import files for download

def evaluate(m, loader):
    m.eval()
    correct = total = 0
    with torch.inference_mode():
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            pred = m(xb).argmax(1)
            correct += (pred == yb).sum().item()
            total += yb.size(0)
    return correct / max(1, total)

EPOCHS = 15  # ⬅️ adjust to 20–30 for ~98% accuracy
best_acc = 0.0
for epoch in range(EPOCHS):
    model.train()
    for xb, yb in train_loader:
        xb, yb = xb.to(device), yb.to(device)
        optimizer.zero_grad()
        loss = criterion(model(xb), yb)
        loss.backward()
        optimizer.step()
    scheduler.step()

    val_acc = evaluate(model, val_loader)
    print(f"Epoch {epoch+1}/{EPOCHS} - val_acc={val_acc:.4f}")
    if val_acc > best_acc:
        best_acc = val_acc
        torch.save(model.state_dict(), "/content/resnet50_fusion.pt")
        with open("/content/classes.txt", "w") as f:
            f.write("\n".join(train_ds.classes))
        print("✅ Saved new best (val_acc=%.4f)" % val_acc)

print("Training complete. Best val_acc=%.4f" % best_acc)

# Add downloadable option for the .pt file
files.download("/content/resnet50_fusion.pt")

# ============================================================
# MULTIMODAL IMAGE TYPE DETECTION (Leaf vs Soil)
# ============================================================

def detect_image_type(pil_img,
                      green_threshold=0.04,
                      brown_threshold=0.06,
                      texture_threshold=250):

    img = np.array(pil_img.convert("RGB"))
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

    # --- GREEN MASK
    lower_green = np.array([25, 40, 20])
    upper_green = np.array([95, 255, 255])
    mask_green = cv2.inRange(hsv, lower_green, upper_green)
    green_ratio = (mask_green > 0).sum() / mask_green.size

    # --- BROWN MASK
    lower_brown = np.array([5, 40, 20])
    upper_brown = np.array([25, 255, 200])
    mask_brown = cv2.inRange(hsv, lower_brown, upper_brown)
    brown_ratio = (mask_brown > 0).sum() / mask_brown.size

    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    texture_variance = np.var(gray)

    # -----------------------------------------
    # Smart Logic (robust to hand presence)
    # -----------------------------------------

    # If strong green presence → Leaf
    if green_ratio > green_threshold:
        return "Leaf"

    # If strong brown OR strong texture → Soil
    if brown_ratio > brown_threshold or texture_variance > texture_threshold:
        return "Soil"

    return "Invalid"

# 5) Severity estimator
def estimate_severity_pil(pil_img):
    img = np.array(pil_img.convert("RGB"))
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    lower_green = np.array([25, 40, 20])
    upper_green = np.array([95, 255, 255])
    mask_green = cv2.inRange(hsv, lower_green, upper_green)
    total = mask_green.size
    green_pixels = (mask_green > 0).sum()
    non_green_ratio = 1.0 - (green_pixels / max(1, total))
    sev = float(np.clip(non_green_ratio, 0, 1))
    if sev < 0.2:
        stage = "Early"
    elif sev < 0.5:
        stage = "Mid"
    else:
        stage = "Late"
    return sev, stage

# ---------- 3) Advice map (with Other Crop fallback) ----------
advice_map = {
    "Tomato_healthy": {
        "summary": "Plant healthy ✅",
        "actions": ["Maintain good irrigation."],
        "prevention": ["Rotate crops."]
    },
    "Tomato_Late_blight": {
        "summary": "Fungal disease.",
        "actions": ["Remove infected leaves.", "Use Mancozeb."],
        "prevention": ["Avoid overhead watering."]
    },
    "Tomato_Early_blight": {
        "summary": "Dark concentric spots.",
        "actions": ["Use fungicides with chlorothalonil."],
        "prevention": ["Rotate crops."]
    },
    "Tomato_Septoria_leaf_spot": {
        "summary": "Small dark spots.",
        "actions": ["Remove leaves.", "Apply copper fungicides."],
        "prevention": ["Keep leaves dry."]
    },
    "Tomato_Tomato_mosaic_virus": {
        "summary": "Viral disease.",
        "actions": ["Destroy infected plants."],
        "prevention": ["Disinfect tools."]
    },
    "Potato_Early_blight": {
        "summary": "Brown spots with rings.",
        "actions": ["Apply Mancozeb."],
        "prevention": ["Field sanitation."]
    },
    "Potato_Late_blight": {
        "summary": "Dark lesions.",
        "actions": ["Destroy plants.", "Apply fungicides."],
        "prevention": ["Avoid wet conditions."]
    },
    "Potato_healthy": {
        "summary": "Plant healthy ✅",
        "actions": ["No treatment needed."],
        "prevention": ["Good soil management."]
    },
    "Pepper_bell_Bacterial_spot": {
        "summary": "Bacterial leaf spots.",
        "actions": ["Use copper bactericides."],
        "prevention": ["Rotate crops."]
    },
    "Pepper_bell_healthy": {
        "summary": "Plant healthy ✅",
        "actions": ["Standard care."],
        "prevention": ["Monitor regularly."]
    },
    "Corn_Blight": {
        "summary": "Fungal disease causing large oval or irregular gray-green lesions on leaves.",
        "actions": ["Apply fungicides containing Mancozeb or Chlorothalonil at early symptoms."],
        "prevention": ["Rotate crops with non-host plants.", "Plant resistant corn varieties."]
    },
    "Corn_Common_Rust": {
        "summary": "Rust fungus producing reddish-brown pustules on upper and lower leaf surfaces.",
        "actions": ["Scout regularly and treat at early infection stages."],
        "prevention": ["Plant early to avoid peak rust pressure.", "Improve field airflow with proper spacing."]
    },
    "Corn_Gray_Leaf_Spot": {
        "summary": "Gray rectangular lesions that merge, reducing photosynthesis and yield.",
        "actions": ["Remove infected residue after harvest."],
        "prevention": ["Practice crop rotation.", "Avoid excessive nitrogen which promotes lush foliage."]
    },
    "Corn_Healthy": {
        "summary": "Corn crop is healthy.",
        "actions": [
            "Continue recommended irrigation and fertilization schedule.",
            "Scout regularly to detect diseases early."
        ],
        "prevention": ["Use certified disease-free seeds.", "Maintain good field hygiene."]
    },
    "Rice_Bacterial_leaf_blight": {
        "summary": "Bacterial disease causing yellowing and wilting of leaves from tip downwards.",
        "actions": ["Apply copper-based bactericides.", "Avoid injuring plants during cultivation."],
        "prevention": ["Use resistant rice varieties.", "Ensure proper water management to reduce disease spread."]
    },
    "Rice_Brown_spot": {
        "summary": "Fungal disease causing brown circular spots with gray centers on leaves.",
        "actions": ["Improve field drainage to avoid waterlogging."],
        "prevention": ["Plant resistant rice varieties.", "Maintain proper plant spacing for air circulation."]
    },
    "Rice_Leaf smut": {
        "summary": "Fungal disease causing black sooty spots on leaves, reducing photosynthesis.",
        "actions": ["Remove severely infected plants to minimize spread."],
        "prevention": ["Use clean and disease-free seeds.", "Maintain proper nutrition to boost plant resistance."]
    },
    "Black_Soil": {
        "summary": "Clay-rich soil with high moisture retention, rich in lime, iron and magnesium. Ideal for long-duration crops.",
        "ph_range": "7.0 – 8.5",
        "water_requirement": "Low to Moderate (retains moisture well)",
        "npk_recommendation_kg_per_ha": {
            "Nitrogen (N)": "80 – 120",
            "Phosphorus (P)": "40 – 60",
            "Potassium (K)": "40 – 50"
        },
        "recommended_crops": [
            "Cotton",
            "Soybean",
            "Sunflower",
            "Millets",
            "Pulses"
        ]
    },

    "Cinder_Soil": {
        "summary": "Volcanic-origin porous soil with good drainage but low nutrient holding capacity.",
        "ph_range": "6.0 – 7.5",
        "water_requirement": "Moderate to High (due to high drainage)",
        "npk_recommendation_kg_per_ha": {
            "Nitrogen (N)": "120 – 160",
            "Phosphorus (P)": "60 – 80",
            "Potassium (K)": "50 – 70"
        },
        "recommended_crops": [
            "Vegetables",
            "Maize",
            "Groundnut",
            "Pulses",
            "Fruit crops"
        ]
    },

    "Laterite_Soil": {
        "summary": "Iron and aluminum-rich soil with low organic matter; requires fertilizer support.",
        "ph_range": "5.0 – 6.5",
        "water_requirement": "Moderate",
        "npk_recommendation_kg_per_ha": {
            "Nitrogen (N)": "130 – 170",
            "Phosphorus (P)": "60 – 90",
            "Potassium (K)": "60 – 90"
        },
        "recommended_crops": [
            "Tea",
            "Coffee",
            "Cashew",
            "Rubber",
            "Coconut"
        ]
    },

    "Peat_Soil": {
        "summary": "High organic matter soil with high water retention but acidic nature.",
        "ph_range": "3.5 – 5.5",
        "water_requirement": "Low (naturally retains water)",
        "npk_recommendation_kg_per_ha": {
            "Nitrogen (N)": "60 – 100",
            "Phosphorus (P)": "50 – 70",
            "Potassium (K)": "40 – 60"
        },
        "recommended_crops": [
            "Rice",
            "Vegetables",
            "Carrot",
            "Onion",
            "Spinach"
        ]
    },

    "Yellow_Soil": {
        "summary": "Light-textured soil with moderate fertility and good drainage.",
        "ph_range": "5.5 – 7.0",
        "water_requirement": "Moderate",
        "npk_recommendation_kg_per_ha": {
            "Nitrogen (N)": "110 – 150",
            "Phosphorus (P)": "50 – 70",
            "Potassium (K)": "50 – 70"
        },
        "recommended_crops": [
            "Groundnut",
            "Potato",
            "Pulses",
            "Maize",
            "Millets"
        ]
    },
    "Other_Crop": {
        "summary": "The model detected a leaf, but not Tomato/Potato/Pepper/Rice/Corn.",
        "actions": ["Currently, only Tomato, Potato, Corn, Rice and Pepper are supported."],
        "prevention": ["Try uploading a supported crop leaf."]
    }

}
with open("/content/advice.json", "w") as f:
    json.dump(advice_map, f, indent=2)

# 6) Inference helpers
def load_model(model_path="/content/resnet50_fusion.pt", classes_path="/content/classes.txt"):
    classes = Path(classes_path).read_text().splitlines()
    m = tv.models.resnet50(weights=None)
    m.fc = nn.Linear(m.fc.in_features, len(classes))
    m.load_state_dict(torch.load(model_path, map_location=device))
    m.eval().to(device)
    return m, classes

infer_tfm = tv.transforms.Compose([
    tv.transforms.Resize(256),
    tv.transforms.CenterCrop(224),
    tv.transforms.ToTensor(),
    tv.transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

MODEL, CLASSES = load_model()
ADVICE = json.loads(Path("/content/advice.json").read_text())

# 🔑 Normalize class label for advice lookup
def normalize_label(label: str):
    return (
        label.strip()
             .replace(" ", "_")
             .replace("-", "_")
             .replace("___", "_")
             .replace("__", "_")
    )


def is_soil_image(pil_img, brown_threshold=0.08):
    """
    Rough soil detection using brown pixel ratio.
    """
    img = np.array(pil_img.convert("RGB"))
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

    # brown color range
    lower_brown = np.array([10, 40, 20])
    upper_brown = np.array([25, 255, 200])

    mask_brown = cv2.inRange(hsv, lower_brown, upper_brown)
    brown_ratio = (mask_brown > 0).sum() / mask_brown.size

    return brown_ratio > brown_threshold

def center_crop_focus(pil_img):
    img = np.array(pil_img)
    h, w, _ = img.shape

    # Crop central 70% region
    crop = img[
        int(h*0.15):int(h*0.85),
        int(w*0.15):int(w*0.85)
    ]

    return Image.fromarray(crop)


@torch.inference_mode()
def predict_image(pil_img: Image.Image):

    x = infer_tfm(pil_img).unsqueeze(0).to(device)

    logits = MODEL(x)
    probs = torch.softmax(logits, dim=1)[0].cpu().numpy()

    # Get top-2 predictions
    top2 = np.argsort(probs)[-2:][::-1]
    idx1, idx2 = top2[0], top2[1]

    label1 = CLASSES[idx1]
    conf1 = float(probs[idx1])
    conf2 = float(probs[idx2])

    norm_label = normalize_label(label1)

    # -----------------------------
    # SMART CONFIDENCE LOGIC
    # -----------------------------
    confidence_margin = conf1 - conf2

    # If prediction is very weak AND margin small → invalid
    if conf1 < 0.40 or confidence_margin < 0.10:
        return {
            "type": "Invalid",
            "label": "Invalid Input",
            "confidence": conf1,
            "severity_score": 0.0,
            "severity_stage": "N/A",
            "advice": {
                "summary": "The image is not clearly recognized as supported soil or crop.",
                "actions": ["Upload a clear soil surface or crop leaf image."],
                "prevention": []
            }
        }

    # -----------------------------
    # TYPE DECISION BY CLASS NAME
    # -----------------------------
    soil_classes = {
        "Black_Soil",
        "Cinder_Soil",
        "Laterite_Soil",
        "Peat_Soil",
        "Yellow_Soil"
    }

    if norm_label in soil_classes:

        rec = ADVICE.get(norm_label)

        return {
            "type": "Soil",
            "label": norm_label,
            "confidence": conf1,
            "severity_score": 0.0,
            "severity_stage": "N/A",
            "advice": rec
        }

    else:
        sev_score, stage = estimate_severity_pil(pil_img)
        rec = ADVICE.get(norm_label, ADVICE.get("Other_Crop"))

        return {
            "type": "Leaf",
            "label": norm_label,
            "confidence": conf1,
            "severity_score": sev_score,
            "severity_stage": stage,
            "advice": rec
        }

def gradio_predict(img: Image.Image):

    result = predict_image(img)
    advice = result.get("advice", {})

    # =========================================
    # 🌿 LEAF OUTPUT
    # =========================================
    if result["type"] == "Leaf":

        text = (
            f"🌿 Leaf Disease Detection\n\n"
            f"🩺 Class: {result['label']}\n"
            f"📊 Confidence: {result['confidence']*100:.2f}%\n"
            f"🌡 Severity: {result['severity_stage']} "
            f"(score {result['severity_score']:.2f})\n\n"
            f"📝 {advice.get('summary','')}\n\n"
            f"🔧 Actions:\n"
            + "\n".join([f"• {a}" for a in advice.get('actions', [])])
            + "\n\n🛡 Prevention:\n"
            + "\n".join([f"• {p}" for p in advice.get('prevention', [])])
        )

    # =========================================
    # 🌍 SOIL OUTPUT
    # =========================================
    elif result["type"] == "Soil":

        npk = advice.get("npk_recommendation_kg_per_ha", {})
        crops = advice.get("recommended_crops", [])

        text = (
            f"🌍 Soil Classification\n\n"
            f"🧪 Soil Type: {result['label']}\n"
            f"📊 Confidence: {result['confidence']*100:.2f}%\n\n"
            f"📌 Soil Details:\n"
            f"• pH Range: {advice.get('ph_range','N/A')}\n"
            f"• Water Requirement: {advice.get('water_requirement','N/A')}\n"
            f"• Nitrogen (N): {npk.get('Nitrogen (N)','N/A')}\n"
            f"• Phosphorus (P): {npk.get('Phosphorus (P)','N/A')}\n"
            f"• Potassium (K): {npk.get('Potassium (K)','N/A')}\n\n"
            f"🌾 Recommended Crops:\n"
            + "\n".join([f"• {c}" for c in crops])
        )

    # =========================================
    # ⚠️ INVALID / UNCERTAIN OUTPUT
    # =========================================
    else:

        text = (
            f"⚠️ Invalid or Uncertain Input\n\n"
            f"Confidence: {result['confidence']*100:.2f}%\n\n"
            f"{advice.get('summary','')}\n\n"
            + "\n".join([f"• {a}" for a in advice.get('actions', [])])
        )

    return {result['label']: result['confidence']}, text




demo = gr.Interface(
    fn=gradio_predict,
    inputs=gr.Image(type="pil", label="Upload Leaf or Soil Image"),
    outputs=[
        gr.Label(label="Prediction Confidence"),
        gr.Markdown()
    ],
    title="🌱 Intelligent Multimodal Agricultural Assistant (Fusion Model)",
    description="""
Single ResNet-50 Fusion Model:
• 🌿 Leaf Disease Detection + Severity
• 🌍 Soil Classification + NPK + Crop Recommendation
"""
)

demo.launch(share=True, debug=False)

